local addonName, ns = ...
local HC = ns.HammerCore

-- The lore quiz library, shared by every addon.  Each entry is
--   { "Question", "Correct answer", "Wrong", "Wrong", "Wrong",
--     era = "both" | "classic" | "retail", class = "PALADIN"?, race = "Dwarf"? }
-- The correct answer is always written second; the quiz shuffles choices.
--   era "both"    true in Classic (WoW Forever) and Retail
--   era "classic" true only in the Classic world, e.g. before the Cataclysm
--   era "retail"  depends on content after Classic
-- class and race use the client's file tokens (UnitClass, UnitRace), and a
-- tagged question only reaches a matching character.
-- Keep every fact checkable: a wrong answer in a quiz is worse than no quiz.

HC.QUIZ = {
    -- ── Geography: true in both worlds ─────────────────────────────────────
    { "Which zone surrounds Ironforge?", "Dun Morogh", "Elwynn Forest", "Loch Modan", "Wetlands" },
    { "Which is closest to Ironforge?", "Kharanos", "Goldshire", "Lakeshire", "Southshore" },
    { "Which zone borders Dun Morogh to the east?", "Loch Modan", "Westfall", "Duskwood", "Redridge Mountains" },
    { "Goldshire lies in which zone?", "Elwynn Forest", "Westfall", "Duskwood", "Redridge Mountains" },
    { "Lakeshire lies in which zone?", "Redridge Mountains", "Elwynn Forest", "Loch Modan", "Swamp of Sorrows" },
    { "Darkshire lies in which zone?", "Duskwood", "Darkshore", "Deadwind Pass", "Redridge Mountains" },
    { "The Deadmines lie beneath which Westfall village?", "Moonbrook", "Sentinel Hill", "Goldshire", "Darkshire" },
    { "Gadgetzan lies in which zone?", "Tanaris", "Feralas", "Thousand Needles", "Un'Goro Crater" },
    { "Which goblin cartel runs Booty Bay?", "Steamwheedle Cartel", "Bilgewater Cartel", "Venture Company", "Blackwater Raiders" },
    { "Menethil Harbor lies in which zone?", "Wetlands", "Arathi Highlands", "Loch Modan", "Hillsbrad Foothills" },
    { "Theramore lies in which zone?", "Dustwallow Marsh", "Swamp of Sorrows", "Durotar", "Tanaris" },
    { "Uldaman lies in which zone?", "Badlands", "Searing Gorge", "Loch Modan", "Tanaris" },
    { "Shadowfang Keep lies in which zone?", "Silverpine Forest", "Tirisfal Glades", "Duskwood", "Alterac Mountains" },
    { "Stratholme lies in which zone?", "Eastern Plaguelands", "Western Plaguelands", "Tirisfal Glades", "Hillsbrad Foothills" },
    { "Scholomance lies within which keep?", "Caer Darrow", "Hearthglen", "Tyr's Hand", "Light's Hope Chapel" },
    { "Ahn'Qiraj lies in which zone?", "Silithus", "Tanaris", "Un'Goro Crater", "Feralas" },
    { "Molten Core lies inside which mountain?", "Blackrock Mountain", "Grim Batol", "Mount Hyjal", "Thunder Bluff" },
    { "Ragefire Chasm lies beneath which city?", "Orgrimmar", "Thunder Bluff", "Undercity", "Stormwind" },
    { "The Undercity lies beneath the ruins of which city?", "Lordaeron", "Stratholme", "Dalaran", "Gilneas" },
    { "Cenarion Hold stands in which zone?", "Silithus", "Moonglade", "Ashenvale", "Felwood" },
    { "The Sunwell lies in which kingdom?", "Quel'Thalas", "Lordaeron", "Gilneas", "Stromgarde" },
    { "Which trolls built Zul'Aman?", "Amani", "Gurubashi", "Darkspear", "Drakkari" },

    -- ── Lore: true in both worlds ──────────────────────────────────────────
    { "Orgrimmar is named after which orc?", "Orgrim Doomhammer", "Durotan", "Grom Hellscream", "Blackhand" },
    { "Who was Thrall's father?", "Durotan", "Orgrim Doomhammer", "Grom Hellscream", "Kargath Bladefist" },
    { "Who kept the young Thrall as a gladiator slave?", "Aedelas Blackmoore", "Terenas Menethil", "Anduin Lothar", "Othmar Garithos" },
    { "Which orc shaman taught Thrall the ways of the elements?", "Drek'Thar", "Ner'zhul", "Gul'dan", "Rehgar Earthfury" },
    { "Which clan did Durotan lead?", "Frostwolf", "Warsong", "Blackrock", "Shattered Hand" },
    { "Which clan did Grom Hellscream lead?", "Warsong", "Frostwolf", "Bleeding Hollow", "Dragonmaw" },
    { "Which orc warlock helped Medivh open the Dark Portal?", "Gul'dan", "Ner'zhul", "Cho'gall", "Kilrogg Deadeye" },
    { "Who was the last Guardian of Tirisfal?", "Medivh", "Aegwynn", "Khadgar", "Antonidas" },
    { "Karazhan was the tower of which mage?", "Medivh", "Khadgar", "Antonidas", "Kel'Thuzad" },
    { "Which city did the Horde sack in the First War?", "Stormwind", "Lordaeron", "Dalaran", "Ironforge" },
    { "Who assassinated King Llane Wrynn?", "Garona", "Gul'dan", "Orgrim Doomhammer", "Blackhand" },
    { "Which city holds the Kirin Tor's seat of magic?", "Dalaran", "Stormwind", "Lordaeron", "Kul Tiras" },
    { "Kel'Thuzad was once a member of which order?", "Kirin Tor", "Cenarion Circle", "Argent Dawn", "Scarlet Crusade" },
    { "Which city did Arthas purge in the Culling?", "Stratholme", "Andorhal", "Hearthglen", "Southshore" },
    { "Which king of Lordaeron was slain by his own son?", "Terenas Menethil", "Llane Wrynn", "Genn Greymane", "Thoras Trollbane" },
    { "Which runeblade did Arthas claim in Northrend?", "Frostmourne", "Ashbringer", "Doomhammer", "Gorehowl" },
    { "Who created the Scourge?", "The Lich King", "Kel'Thuzad", "Sylvanas Windrunner", "Archimonde" },
    { "Which citadel was built around the Frozen Throne?", "Icecrown Citadel", "Naxxramas", "Utgarde Keep", "Drak'Tharon Keep" },
    { "Which paladin is called the Lightbringer?", "Uther", "Tirion Fordring", "Turalyon", "Bolvar Fordragon" },
    { "What does the Argent Dawn fight above all?", "The Scourge", "The Burning Legion", "The Black Dragonflight", "The Horde" },
    { "Who leads the Burning Legion?", "Sargeras", "Kil'jaeden", "Archimonde", "Mannoroth" },
    { "The Well of Eternity's implosion caused which event?", "The Sundering", "The Third War", "The Cataclysm", "The War of the Shifting Sands" },
    { "Which Old God was sealed beneath Ahn'Qiraj?", "C'Thun", "Yogg-Saron", "N'Zoth", "Y'Shaarj" },
    { "Hakkar is known by which title?", "the Soulflayer", "the Houndmaster", "the Betrayer", "the Destroyer" },
    { "Which troll tribe served Hakkar in Zul'Gurub?", "Gurubashi", "Darkspear", "Amani", "Drakkari" },
    { "Which dragon Aspect was called the Earth-Warder?", "Neltharion", "Malygos", "Nozdormu", "Ysera" },
    { "Which Aspect leads the red dragonflight?", "Alexstrasza", "Ysera", "Sindragosa", "Onyxia" },
    { "Onyxia is the daughter of which dragon?", "Deathwing", "Malygos", "Nozdormu", "Nefarian" },
    { "Nozdormu is the Aspect of which dragonflight?", "Bronze", "Blue", "Green", "Black" },
    { "Ysera was the Aspect of which dragonflight?", "Green", "Red", "Blue", "Bronze" },
    { "Malygos was the Aspect of which dragonflight?", "Blue", "Black", "Bronze", "Red" },
    { "Who is master of Blackwing Lair?", "Nefarian", "Onyxia", "Ragnaros", "Vaelastrasz" },
    { "Ragnaros is the Firelord. Which element does he rule?", "Fire", "Earth", "Water", "Air" },
    { "Who is the high priestess of Elune?", "Tyrande Whisperwind", "Maiev Shadowsong", "Shandris Feathermoon", "Fandral Staghelm" },
    { "Who is Malfurion Stormrage's twin brother?", "Illidan", "Fandral", "Xavius", "Cenarius" },
    { "Who taught the night elves the ways of the druid?", "Cenarius", "Elune", "Malorne", "Goldrinn" },
    { "Who was Illidan's jailer for ten thousand years?", "Maiev Shadowsong", "Tyrande Whisperwind", "Shandris Feathermoon", "Jarod Shadowsong" },
    { "Magni Bronzebeard was king of which city?", "Ironforge", "Grim Batol", "Gnomeregan", "Stormwind" },
    { "Which Bronzebeard brother is the famous explorer?", "Brann", "Muradin", "Magni", "Dagran" },
    { "Who leads the gnomes?", "Gelbin Mekkatorque", "Sicco Thermaplugg", "Brann Bronzebeard", "Muradin Bronzebeard" },
    { "Gnomeregan fell to an invasion of which creatures?", "Troggs", "Kobolds", "Gnolls", "Murlocs" },
    { "Who was Jaina Proudmoore's father?", "Daelin Proudmoore", "Derek Proudmoore", "Terenas Menethil", "Antonidas" },
    { "Which city did Jaina found in Kalimdor?", "Theramore", "Northwatch", "Nijel's Point", "Feathermoon Stronghold" },
    { "Stormwind's great cathedral is the Cathedral of what?", "Light", "Elune", "the Sun", "the Tides" },
    { "Thunder Bluff is the capital of which people?", "Tauren", "Orcs", "Trolls", "Forsaken" },
    { "Durotar is named after which orc?", "Durotan", "Doomhammer", "Draka", "Drek'Thar" },

    -- ── Classic world only (WoW Forever) ───────────────────────────────────
    { "Who leads the Forsaken?", "Sylvanas Windrunner", "Varimathras", "Nathanos Blightcaller", "Putress", era = "classic" },
    { "Who is Warchief of the Horde?", "Thrall", "Garrosh Hellscream", "Vol'jin", "Grom Hellscream", era = "classic" },
    { "Who is High Chieftain of the tauren?", "Cairne Bloodhoof", "Baine Bloodhoof", "Hamuul Runetotem", "Magatha Grimtotem", era = "classic" },
    { "Who leads the Darkspear trolls?", "Vol'jin", "Sen'jin", "Zalazane", "Rokhan", era = "classic" },
    { "Who rules Stormwind as regent?", "Bolvar Fordragon", "Varian Wrynn", "Katrana Prestor", "Anduin Lothar", era = "classic" },
    { "Darnassus is built upon which world tree?", "Teldrassil", "Nordrassil", "Shaladrassil", "Vordrassil", era = "classic" },
    { "The Crossroads lies in which zone?", "The Barrens", "Durotar", "Stonetalon Mountains", "Mulgore", era = "classic" },
    { "The Wailing Caverns lie in which zone?", "The Barrens", "Ashenvale", "Desolace", "Dustwallow Marsh", era = "classic" },
    { "Booty Bay lies in which zone?", "Stranglethorn Vale", "Tanaris", "Swamp of Sorrows", "Feralas", era = "classic" },
    { "Southshore lies in which zone?", "Hillsbrad Foothills", "Arathi Highlands", "Wetlands", "Alterac Mountains", era = "classic" },
    { "Auberdine lies in which zone?", "Darkshore", "Ashenvale", "Teldrassil", "Feralas", era = "classic" },
    { "Above which zone does Naxxramas hover?", "Eastern Plaguelands", "Western Plaguelands", "Tirisfal Glades", "Dragonblight", era = "classic" },
    { "Who leads the Defias Brotherhood in the Deadmines?", "Edwin VanCleef", "Vanessa VanCleef", "Mr. Smite", "Captain Greenskin", era = "classic" },

    -- ── Retail only ────────────────────────────────────────────────────────
    { "Who is High Chieftain of the tauren today?", "Baine Bloodhoof", "Cairne Bloodhoof", "Hamuul Runetotem", "Magatha Grimtotem", era = "retail" },
    { "Deathwing's return caused which event?", "The Cataclysm", "The Sundering", "The Third War", "The Scourge Invasion", era = "retail" },
    { "Who was Garrosh Hellscream's father?", "Grom Hellscream", "Thrall", "Orgrim Doomhammer", "Broxigar", era = "retail" },
    { "Which blood elf prince led his people to Outland?", "Kael'thas Sunstrider", "Lor'themar Theron", "Anasterian Sunstrider", "Rommath", era = "retail" },
    { "Where did Illidan rule in Outland?", "Black Temple", "Tempest Keep", "Karazhan", "Shattrath City", era = "retail" },
    { "Which continent lay hidden in mists for ten thousand years?", "Pandaria", "Northrend", "Kul Tiras", "Zandalar", era = "retail" },
    { "Which ancient city on the Broken Isles is home to the nightborne?", "Suramar", "Val'sharah", "Azsuna", "Highmountain", era = "retail" },
    { "Zandalar is the homeland of which trolls?", "Zandalari", "Darkspear", "Amani", "Drakkari", era = "retail" },
    { "In the Shadowlands, where does the Arbiter judge souls?", "Oribos", "Bastion", "Revendreth", "The Maw", era = "retail" },
    { "Which lands were revealed in Dragonflight?", "The Dragon Isles", "The Broken Isles", "Khaz Algar", "Zereth Mortis", era = "retail" },
    { "The War Within is set on which continent?", "Khaz Algar", "Northrend", "Zandalar", "Kalimdor", era = "retail" },

    -- ── Race-specific ─────────────────────────────────────────────────────
    { "Northshire Abbey lies in which zone?", "Elwynn Forest", "Westfall", "Duskwood", "Redridge Mountains", race = "Human" },
    { "Where do new dwarves begin their journey?", "Coldridge Valley", "Valley of Trials", "Shadowglen", "Northshire Valley", race = "Dwarf" },
    { "Where do new orcs begin their journey?", "Valley of Trials", "Echo Isles", "Camp Narache", "Deathknell", race = "Orc" },
    { "In which village do the Forsaken awaken?", "Deathknell", "Brill", "Tarren Mill", "Sepulcher", race = "Scourge" },
    { "Where do young tauren begin?", "Camp Narache", "Bloodhoof Village", "Sun Rock Retreat", "Camp Taurajo", race = "Tauren" },
    { "Where do new trolls begin their journey?", "Valley of Trials", "Echo Isles", "Sen'jin Village", "Camp Narache", race = "Troll", era = "classic" },
    { "Where do new trolls begin their journey?", "Echo Isles", "Valley of Trials", "Zuldazar", "Sen'jin Village", race = "Troll", era = "retail" },
    { "Where do new gnomes begin their journey?", "Coldridge Valley", "New Tinkertown", "Gnomeregan", "Kharanos", race = "Gnome", era = "classic" },
    { "Where do new gnomes begin their journey?", "New Tinkertown", "Coldridge Valley", "Kharanos", "Steelgrill's Depot", race = "Gnome", era = "retail" },
    { "Where do new night elves begin their journey?", "Shadowglen", "Coldridge Valley", "Starbreeze Village", "Dolanaar", race = "NightElf", era = "classic" },
    { "The draenei crashed on Azeroth aboard which ship?", "The Exodar", "The Genedar", "The Vindicaar", "The Skyfire", race = "Draenei", era = "retail" },
    { "Where do new blood elves begin?", "Sunstrider Isle", "Silvermoon City", "Falconwing Square", "Tranquillien", race = "BloodElf", era = "retail" },

    -- ── Class-specific ─────────────────────────────────────────────────────
    { "Which blade did Alexandros Mograine wield against the undead?", "Ashbringer", "Frostmourne", "Quel'Delar", "Shalamayne", class = "PALADIN" },
    { "Night elf priests revere which moon goddess?", "Elune", "Eonar", "Aman'Thul", "Norgannon", class = "PRIEST" },
    { "Who led the Kirin Tor through the Second and Third Wars?", "Antonidas", "Khadgar", "Rhonin", "Modera", class = "MAGE" },
    { "Who led the orcs' Shadow Council?", "Gul'dan", "Ner'zhul", "Cho'gall", "Teron Gorefiend", class = "WARLOCK" },
    { "Who was the first mortal druid?", "Malfurion Stormrage", "Cenarius", "Fandral Staghelm", "Hamuul Runetotem", class = "DRUID" },
    { "Who was Ranger-General of Silvermoon?", "Sylvanas Windrunner", "Alleria Windrunner", "Vereesa Windrunner", "Halduron Brightwing", class = "HUNTER" },
    { "SI:7 is the intelligence agency of which kingdom?", "Stormwind", "Lordaeron", "Gilneas", "Kul Tiras", class = "ROGUE" },
    { "Which axe did Grom Hellscream wield?", "Gorehowl", "Doomhammer", "Shadowmourne", "Warglaive of Azzinoth", class = "WARRIOR" },
    { "Who was the first draenei shaman?", "Nobundo", "Velen", "Akama", "Maraad", class = "SHAMAN", era = "retail" },
    { "What was the death knights' first stronghold?", "Acherus: The Ebon Hold", "Light's Hope Chapel", "Icecrown Citadel", "Naxxramas", class = "DEATHKNIGHT", era = "retail" },
    { "Which land is the monk tradition most tied to?", "Pandaria", "Kul Tiras", "Zandalar", "Suramar", class = "MONK", era = "retail" },
    { "Who first trained the demon hunters?", "Illidan Stormrage", "Kayn Sunfury", "Altruis", "Maiev Shadowsong", class = "DEMONHUNTER", era = "retail" },
    { "Evokers belong to which race?", "Dracthyr", "Vulpera", "Earthen", "Nightborne", class = "EVOKER", era = "retail" },
}
